---
output:
  word_document:
    keep_md: true
---



```{r ,echo=FALSE, dev=c('png'), warning=FALSE, dpi=300, fig.width=12, fig.asp=0.6,fig.show='hold', message=FALSE, include=TRUE}
rm(list = ls())
library(haven)
library(ggrepel)
library(expint)
library(latex2exp)
library(tidyverse)
startAge = 50
endAge = 100
source("sampleMH.R")
LE50 = function(lambda, delta) {
  # b0:lambda
  # b1:delta
  (1 / delta) *
    exp(exp(lambda) / delta) *
    (expint::expint(exp(lambda) / delta) - expint::expint(2 / 3 / delta)) +
    1.5 * exp((exp(lambda) - 2 / 3) / delta)
}

files = c("", "1950", "1900")
cc = 'Sweden'

p1Data = map_dfr(c(files), function(ff) {
  map_dfr(c("Male", "Female"), function(ss) {
    load(paste0('Estimates/', startAge, endAge, '/priorA/c', cc, ss, 'B0B1var', ff, '.rData'))
    numParms = 2
    x = result$x
    sigma = result$sigma
    modelCountry = result$modelCountry
    numAllCohort = modelCountry[[1]]$number
    prior_allcohorts = data.frame(t(matrix(x, numParms))) %>%
      `colnames<-`(c("B0", "B1")) %>%
      mutate(
        cohort = modelCountry[[1]]$cohort,
        Sex = ss,
        Country = cc,
        file = ff
      )
  })
})

p3Data = map_dfr(c(files), function(ff) {
  map_dfr(c("Male", "Female"), function(ss) {
    load(paste0('Estimates/', startAge, endAge, '/priorA/c', cc, ss, 'B0B1var', ff, '.rData'))
    numParms = 2
    modelCountry = result$modelCountry
    load(paste0('MH/', startAge, endAge, '/MHc', cc, ss, 'var', ff, '.rData'))
    z = result$zSample
    Total = sum(!is.na(z[1,]))
    sample = z[,seq(burnin + 1,Total,everyTh)]
    xSample = map_dfr(1:dim(sample)[2], function(i) {
      parms = t(matrix(sample[1:(NROW(sample) - 2), i], 2)) %>%
        data.frame() %>%
        `colnames<-`(c("B0", "B1")) %>%
        mutate(
          Country = cc,
          Sex = ss,
          cohort = modelCountry[[1]]$cohort,
          sim = i,
          file = ff
        )
      
    })
  })
}) %>%
  group_by(Country, Sex, sim, file) %>%
  mutate(
    minCohort = min(cohort),
    maxCohort = max(cohort),
    
    minDecade = minCohort + 10 - minCohort %% 10,
    maxDecade = maxCohort - maxCohort %% 10,
    A1 = case_when(
      cohort == minDecade ~ B1[cohort == minCohort],
      cohort <= maxDecade ~ dplyr::lag(B1, n = 10, order_by = cohort),
      TRUE ~ B1[cohort == maxDecade]
    ),
    A0 = case_when(
      cohort == minDecade ~ B0[cohort == minCohort],
      cohort <= maxDecade ~ dplyr::lag(B0, n = 10, order_by = cohort),
      TRUE ~ B0[cohort == maxDecade]
    ),
    gamma0 = B0,
    gamma1 = A1 * (log(2 / 3) - B0) / (log(2 / 3) - A0),
    compression = LE50(gamma0, gamma1) - LE50(A0, A1),
    postponement = LE50(B0, B1) - LE50(gamma0, gamma1),
    gamma = 50 + (log(2 / 3) - B0) / B1
  )


MaximumLivedPeople = read_dta("Data/MaximumLivedPeopleAll.dta") %>%
  dplyr::mutate(
    Country = dplyr::recode(
      dcountry,
      "AUT" = "Austria",
      "AUS" = "Australia",
      "BEL" = "Belgium",
      "CAN" = "Canada",
      "DNK" = "Denmark",
      "FIN" = "Finland",
      "FRA" = "France",
      "DEU" = "Germany",
      "IRE" = "Ireland",
      "ITA" = "Italy",
      "JPN" = "Japan",
      "JAP" = "Japan",
      "NOR" = "Norway",
      "ESP" = "Spain",
      "SWE" = "Sweden",
      "SWZ" = "Switzerland",
      "NET" = "Netherlands",
      "POR" = "Portugal",
      "USA" = "USA",
      "EW" = "UK"
    ),
    Sex = dplyr::recode(sex, "F" = "Female",
                        "M" = "Male"),
    alive = factor(alive, levels = c("N", "Y"))
  ) %>%
  dplyr::rename(cohort = byear) %>%
  dplyr::rename(Alive = alive) %>%
  dplyr::select(Sex, Country, maxage, cohort, Alive)

merged_all_double = map_dfr(c(files), function(ff) {
  map_dfr(c("Male", "Female"), function(ss) {
    read_rds(paste0("Estimates/", startAge, endAge, "/CI/", cc, ss, "CI", ff, ".rds")) %>%
      dplyr::mutate(file = ff)
  })
})


gammas = p3Data %>%
  group_by(Country, Sex, cohort, file) %>%
  dplyr::summarise(upper = quantile(gamma, 0.975),
                   lower = quantile(gamma, 0.025))

CohortLE50 = read_rds("Data/CohortLE50.rds") %>%
  dplyr::rename("cohort" = "YoB") %>%
  dplyr::group_by(Country, Sex) %>%
  dplyr::mutate(
    minCohort = min(cohort),
    minDecade = minCohort + 10 - minCohort %% 10,
    lageLE =  case_when(
      cohort == minDecade ~ LE50[cohort == minCohort],
      TRUE ~ dplyr::lag(LE50, n = 10, order_by = cohort)
    ),
    `LE actual change` = LE50 - lageLE
  ) %>%
  dplyr::filter(cohort %in% seq(1700, 1970, 10))



maxPeriod = 2021
p2Data = merged_all_double %>%
  dplyr::filter(Country == cc) %>%
  dplyr::select(Country, Sex, cohort, upper, lower, file) %>%
  dplyr::mutate(CI = "maxLife") %>%
  bind_rows(gammas %>% filter(Country == cc) %>% mutate(CI = "gamma")) %>%
  dplyr::mutate(file = if_else(file=="","All data",file))

temp = p3Data %>%
  dplyr::mutate(file = if_else(file == "", "All", file)) %>%
  select(B0, B1, gamma, Sex, cohort, sim, file) %>%
  pivot_longer(cols = c(gamma),
               names_to = "type") %>%
  group_by(file, cohort, Sex, type)
```
```{r FigS5, echo=FALSE, dev=c('png'), warning=FALSE, dpi=300, fig.width=12, fig.asp=0.6,fig.show='hold', message=FALSE, include=TRUE}
temp %>%
  dplyr::summarise(
    upper = quantile(value, 0.975, na.rm = TRUE),
    lower = quantile(value, 0.025, na.rm = TRUE)
  )  %>% ggplot(aes(x = cohort)) +
  geom_ribbon(aes(ymax = upper, ymin = lower, fill = file), alpha = 0.5) +
  facet_grid(~ Sex, scales = "free") +
  xlab("Birth year") +
  ylab(TeX(r'($\Lambda_c$)')) +
  scale_x_continuous(breaks = seq(1700, 1975, 20)) +
  coord_cartesian(xlim = c(1700, 1975), ylim = c(95, 150)) +
  theme(
    legend.position = "bottom",
    legend.title = element_text(size = 9),
    legend.text = element_text(size = 9)
  ) +
  scale_fill_discrete(name = "Data used",
                      labels = c("ends in 1900", "ends in 1950", "All"))

```
```{r FigS6, echo=FALSE, dev=c('png'), fig.asp=0.8, fig.show='hold', fig.width=12, message=FALSE, warning=FALSE, dpi=300}
p2 = p2Data %>%
  ggplot() +
  geom_ribbon(aes(
    x = cohort,
    ymin = lower,
    ymax = upper,
    fill = CI
  ), alpha = 0.5) +
  
  facet_grid(file ~ Sex) +
  geom_point(
    data = MaximumLivedPeople %>% filter(Country == cc),
    aes(x = cohort , y = maxage, color = Alive),
    alpha = 0.7
  ) +
  scale_color_manual(
    name = "Longest-lived individual per cohort",
    values = c(1, "springgreen4"),
    labels = c("Dead before 2021", "Alive in 2021"),
    drop = FALSE
  ) +
  scale_fill_manual(
    name = "95% CI’s for",
    values = c(2, 1),
    labels = list(
      TeX(r'($\Lambda_c$ (age at which mortality hazard first reaches 2/3))'),
      TeX(r'($M_c$ (maximum age at death))')
    ),
    drop = FALSE
  ) +
  scale_x_continuous(breaks = seq(1700, 1975, 20)) +
  theme(
    legend.position = "bottom",
    legend.title = element_text(size = 9),
    legend.text = element_text(size = 9)
  ) + 
  ylab("Years") +
  xlab("Birth year") +
  geom_polygon(
    data = data.frame(x = 1700:maxPeriod, y = (maxPeriod - 1700):0) %>% tibble::add_row(x = c(maxPeriod, 1700), y = c(Inf, Inf)),
    aes(x = x, y = y),
    fill = "grey",
    alpha = 0.4
  ) +
  coord_cartesian(xlim = c(1700, 1975), ylim = c(95, 150))

p2
```
```{r FigS7, echo=FALSE, dev=c('png'), fig.asp=0.8, fig.show='hold', fig.width=12, message=FALSE, warning=FALSE, dpi=300}
p3 = p3Data %>% 
  filter(Country == cc) %>%
  dplyr::mutate(file = if_else(file=="","All data",file)) %>%
  filter(cohort %in% c(seq(1700, 1970, 10), max(cohort))) %>%
  mutate(cohort = ifelse(cohort > 1960, 1970, cohort)) %>%
  pivot_longer(cols = c(compression, postponement),
               names_to = "type") %>%
  group_by(file, cohort, Sex, type) %>%
  dplyr::summarise(
    middle = median(value),
    upper.dist = quantile(value, 0.975, na.rm = TRUE) - middle,
    lower.dist = middle - quantile(value, 0.025, na.rm =
                                     TRUE)
  ) %>%
  group_by(file, Sex, cohort) %>%
  arrange(file, Sex, cohort, type) %>%
  dplyr::mutate(
    type = factor(type, levels = c("postponement", "compression")),
    cummean = case_when(cumprod(middle) >= 0 ~ cumsum(middle),
                        TRUE ~ middle),
    ymin = cummean - lower.dist,
    ymax = cummean + upper.dist,
    type = dplyr::recode(type, "compression" = "Due to compression", "postponement" = "Due to postponement")
  ) %>%
  ggplot() +
  geom_bar(aes(
    x = cohort,
    y = middle,
    fill = type,
    group = type
  ), stat = "identity") +
  geom_errorbar(
    aes(
      x = cohort,
      ymin = ymin,
      ymax = ymax,
      fill = type
    ),
    position = position_dodge(10),
    alpha = 0.7
  ) +
  guides(fill = guide_legend(reverse = TRUE)) +
  theme(legend.position = "bottom") +
  theme(legend.title = element_blank()) +
  
  scale_x_continuous(limits = c(1700, 1975),
                     breaks = seq(1700, 1975, 20)) +
  geom_point(
    data = CohortLE50 %>% filter(Country == cc),
    aes(x = cohort, y = `LE actual change`, shape = "Actual change in remaining life expectancy at 50")
  ) +
  facet_grid(file ~ Sex) +
  xlab("Birth year (end of 10-year period)") +
  ylab(
    "Change in remaining life expectancy at age 50 \n relative to cohort born 10 years earlier (years)"
  )

p3
```



