---
output:
  word_document:
    keep_md: true
---



```{r, echo = FALSE, results = 'asis', warning=FALSE, message=FALSE}
rm(list=ls())
library(haven)
library(ggrepel)
library(expint)
library(latex2exp)
library(tidyverse)
library(ggh4x)


cc = "USA"
startAge = 50

temp = map_dfr(c(100,110), function(endAge){
  map_dfr(c(1,2/3), function(mumax){
  map_dfr(c("Male","Female"), function(ss){
  path = paste0("Estimates/",startAge,endAge,"/CI/")
  files = list.files(path)
  filename = paste0(cc,ss,"CI",ifelse(mumax==1,"One",""),".rds")
  if (filename %in% files) read_rds(paste0("Estimates/",startAge,endAge,"/CI/",cc,ss,"CI",ifelse(mumax==1,'One',''),".rds"))
}) %>% mutate(mumax = mumax, parm = paste0(startAge,endAge)) 
})
}) 
```
```{r Fig9, echo=FALSE, dev=c('png'), warning=FALSE, dpi=300, fig.width=12, fig.asp=0.6,fig.show='hold', message=FALSE, include=TRUE}
maxPeriod = 2021

temp %>% 
   mutate(parm = ifelse(parm=="50100", "age 50-100,", "age 50-110,"),
          mumax = ifelse(mumax==1,"hazard rate = 1","hazard rate = 2/3")) %>%
  ggplot() +
  geom_ribbon(aes(
    x = cohort,
    ymin = lower,
    ymax = upper,
    fill = interaction(parm,mumax),
    color = interaction(parm,mumax)
  ), alpha = 0.3, outline.type = "both") +
  
  facet_grid( ~ Sex) +
  scale_x_continuous(breaks = seq(1700, 1975, 20)) +
  theme(
    legend.position = "bottom",
    legend.title = element_text(size = 9),
    legend.text = element_text(size = 9)
  ) +
  ylab("Years") +
  xlab("Birth year") +
  geom_polygon(
    data = data.frame(x = 1700:maxPeriod, y = (maxPeriod - 1700):0) %>% tibble::add_row(x = c(maxPeriod, 1700), y = c(Inf, Inf)),
    aes(x = x, y = y),
    fill = "grey",
    alpha = 0.4
  ) +
  coord_cartesian(xlim = c(1700, 1975), ylim = c(95, 150)) +
  guides(color = guide_legend(title = "Estimated off")) +
  guides(fill = guide_legend(title = "Estimated off"))


```